package Server;

public enum MessageType {
    DOES_USERNAME_EXIST,LOGIN,ERROR,SELLER_ADD_BALANCE,DOES_SELLER_HAVE_LOG,SELLER_SELL_HISTORY,REMOVE_PRODUCT_FROM_OFF,
    ADD_PRODUCT_TO_OFF,DOES_SELLER_HAVE_OFF,DOES_SELLER_HAVE_PRODUCT,EDIT_OFF,EDIT_PRODUCT,ADD_PRODUCT,REMOVE_PRODUCT_SELLER,ADD_BALANCE, GET_CART
    ,INCREASE_PRODUCT, DECREASE_PRODUCT,GET_CART_PRICE
}
